# Generated by Django 6.0.1 on 2026-01-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('event', 'student', 'date')},
        ),
    ]
