# Generated by Django 6.0.1 on 2026-01-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Is the session currently live for attendance?'),
        ),
    ]
